# Use Circle CI Version 2.1 - Illustrate usage of Orb
version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.3
  node: circleci/node@19.10.0
jobs:
  install-node:
  docker:
    - image: 'cimg/base:stable'
  steps:
    - checkout
    - node/Install:
        install-yarn: true
    - run: node --version

      
