# Use Circle CI Version 2.1 - Illustrate usage of Orb
version: 2.1
orbs: 
  aws-ecr: circleci/aws-ecr@6.15.3
  aws-ecs: circleci/aws-ecs@2.0.0

workflows:
  build-and-deploy-docker-image:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY          
          region: AWS_DEFAULT_REGION
          create-repo: false
          dockerfile: Dockerfile
          no-output-timeout: 20m
          path: ../Dockerfile
          repo: nonprod-test-nowsite                     
         
      

      
