# Use Circle CI Version 2.1 - Illustrate usage of Orb
version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.3
  aws-ecr: circleci/aws-ecr@6.15.3
  aws-ecs: circleci/aws-ecs@2.0.0

workflows:
  build-and-deploy-docker-image:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL_ENV_VAR_NAME
          aws-access-key-id: ACCESS_KEY_ID_ENV_VAR_NAME
          aws-secret-access-key: SECRET_ACCESS_KEY_ENV_VAR_NAME          
          create-repo: false
          dockerfile: Dockerfile
          no-output-timeout: 20m
          path: ../Dockerfile          
          region: AWS_REGION_ENV_VAR_NAME
          repo: nonprod-test-nowsite
          skip-when-tags-exist: false
          tag: 'latest,myECRRepos-circleci'
      

      
