# Use Circle CI Version 2.1 - Illustrate usage of Orb
version: 2.1

# Start - 
orbs:   
  aws-ecr: circleci/aws-ecr@6.15.3
  aws-ecs: circleci/aws-ecs@2.0.0

workflows:
  build-and-deploy-docker-image:
    jobs:
      - job-name1 
jobs:
  job-name1:
    machine: 
      image: ubuntu-2004:202101-01
    steps:
      - run: echo "this is test1"
      - run: pwd; ls -ltr; 
      - run: uname -a      
      - run: aws --version --output text
      # AssumeRole - ASR
      #- run: ASR="$(aws sts assume-role --role-arn arn:aws:iam::317367993082:role/bm-super --role-session-name ecr-accessx1 --output text)" 
      - run: ASR=$(aws sts assume-role --role-arn arn:aws:iam::317367993082:role/bm-super --role-session-name ecr-access-x1 --output text)
      # - run: aws sts assume-role --role-arn arn:aws:iam::317367993082:role/bm-super --role-session-name ecr-access-x1 --output text > test
      #- run: cat test
      #- run: ASR=$(cat test)
      - run: echo "$ASR"
      - run: pwd; ls -ltr; id
      
    
    # End
