# Use Circle CI Version 2.1 - Illustrate usage of Orb
version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.3
  aws-ecr: circleci/aws-ecr@6.15.3
  aws-ecs: circleci/aws-ecs@2.0.0
jobs:  
  build: 
    steps:   
      - run: echo "contains only aws-cli"
      - run: id; uname -a;
workflows:
  build-and-deploy-docker-image:
    jobs:
      - aws-ecr/build-and-push-image:
          repo: "${AWS_RESOURCE_NAME_PREFIX}"
          tag: "${CIRCLE_SHA1}"
      

      
