# Use Circle CI Version 2.1 - Illustrate usage of Orb
version: 2.1
orbs: 
  aws-ecr: circleci/aws-ecr@6.15.3
  aws-ecs: circleci/aws-ecs@2.0.0
  
Jobs:
  RunAdHocCommands:
    steps: 
      - run: 
          name: linux commands
          command: env  

workflows:
  version: 2
  build-and-deploy-docker-image:   
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          profile-name: bm-dig
          region: AWS_DEFAULT_REGION          
          repo: nonprod-test-nowsite-1                  
          create-repo: false
          dockerfile: Dockerfile
          no-output-timeout: 20m
          skip-when-tags-exist: false
          tag: 'latest,myECRRepoTag'
          requires:
            - RunAdHocCommands
          
         
      
          
          
         
      

      
